version: 2.1

orbs:
  node: circleci/node@7.1.1

workflows:
  test:
    jobs:
      - node/test:
          matrix:
            parameters:
              run-command:
                - build
                - check
                - lint
                - test
